### PR TITLE
Add SIB17 parsing

### PR DESCRIPTION
**Pull request by matan1008**
This change will allow configuring SIB17, tested by reading the SIBs with wireshark.

Thanks a lot!

### CODE REVIEW

**Comment by andrepuschmann** [comment]
Thanks for this. But too be honest, I don't see a practical use case for it - we don't do any Wifi offloading. Closing PR, feel free to reopen if you see a use for it.

**Comment by matan1008** [comment]
Out of curiosity - why can't we do offloading?

**Comment by andrepuschmann** [comment]
I am not very familiar with the full mechanism. Is it just adding the SIB and then the UE does all what is needed out of the box? Or is there anything else needed?

**Comment by matan1008** [comment]
I am not familiar with this either, just thought it would be a nice starting point for everyone (including future me) who want to develop this area

**Pull request closed without merging**
